# Generated by Django 4.1.7 on 2023-03-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='date_sent',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='date_created',
            field=models.DateTimeField(default=None),
        ),
    ]
