# Generated by Django 4.1.7 on 2023-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_emails_date_sent_emailtemplate_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(),
        ),
    ]
