# Generated by Django 4.1.7 on 2023-03-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='customer',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
