# Generated by Django 4.1.7 on 2023-03-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_customer_emails_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='email_address',
        ),
    ]
