# Generated by Django 4.1.7 on 2023-03-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_emails_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='email_address',
            field=models.ForeignKey(default='email@email', on_delete=django.db.models.deletion.CASCADE, to='campaigns.customer'),
            preserve_default=False,
        ),
    ]
